networks:
  pulp:
    name: "pulp"

volumes:
  pulp-ui-claude-config:

services:
  pulp-ui:
    image: localhost/devcontainer-pulp-ui:latest
    build:
      dockerfile: ./Dockerfile
    security_opt:
      - "label=disable"
    userns_mode: "keep-id"
    environment:
      CLAUDE_CODE_USE_VERTEX: "1"
      CLOUD_ML_REGION: ${CLOUD_ML_REGION:-us-east5}
      ANTHROPIC_VERTEX_PROJECT_ID: ${ANTHROPIC_VERTEX_PROJECT_ID}
    command: /bin/sh -c "while sleep 1000; do :; done"
    volumes:
      - ${UI_PACKAGES_REDHAT_COM_PATH:-~/git/pulp/ui-packages.redhat.com}:/workspace:cached
      - pulp-ui-claude-config:/home/vscode/.claude
      - ${HOME}/.config/gcloud:/home/vscode/.config/gcloud:cached
      - ${HOME}/.vite-plugin-mkcert:/home/vscode/.vite-plugin-mkcert:cached
    networks:
      - pulp
