networks:
  rhtas:
    name: "rhtas"

volumes:
  rhtas-console-ui-claude-config:

services:
  rhtas-console-ui:
    image: localhost/devcontainer-rhtas-console-ui:latest
    build:
      dockerfile: ./Dockerfile
    security_opt:
      - "label=disable"
    userns_mode: "keep-id"
    environment:
      CONSOLE_API_URL: http://rhtas-console:8080
      CLAUDE_CODE_USE_VERTEX: "1"
      CLOUD_ML_REGION: ${CLOUD_ML_REGION:-us-east5}
      ANTHROPIC_VERTEX_PROJECT_ID: ${ANTHROPIC_VERTEX_PROJECT_ID}
    command: /bin/sh -c "while sleep 1000; do :; done"
    volumes:
      - ${RHTAS_CONSOLE_UI_PATH:-~/git/securesign/rhtas-console-ui}:/workspace:cached
      - ./postCreateCommand.sh:/tmp/postCreateCommand.sh:Z
      - rhtas-console-ui-claude-config:/home/vscode/.claude
      - ${HOME}/.config/gcloud:/home/vscode/.config/gcloud:cached
    networks:
      - rhtas
